### ISSUE TITLE
Problem when renaming a folder on the mounted drive [Windows]

### ISSUE THREAD

**Issue by lowleveldesign** [billziss-gh/objfs#1]
Hello, it looks like renaming folders/files on the mounted drives does not work. The error I get looks as follows:

![image](https://user-images.githubusercontent.com/6109268/38245597-003479c4-373f-11e8-89d4-100eca63af14.png)

Thanks for help!

**Comment by billziss-gh** [comment]
Thanks for the report. I am on vacation and will not have much time to investigate until next week.

**Comment by lowleveldesign** [comment]
Sure, thanks. Please let me know if you need more details.

**Comment by billziss-gh** [comment]
@lowleveldesign apologies for late response. I have tried many times, but cannot reproduce this problem. Are you trying this against the latest builds?

**Comment by lowleveldesign** [comment]
@billziss-gh no problem. I'm using the latest source of objfs (compiled with make.cmd) and winsfp 2018.1 B2 from [here](https://github.com/billziss-gh/winfsp/releases). The system I tried is Windows Server 2012 R2 (6.3 Build 9600).

**Comment by billziss-gh** [comment]
Can you please send me full list of steps to repro? I cannot reproduce this in the latest builds (I am testing against Win10 although I would not expect this to make a difference).

If the problem persists, you can also build objfs with `make debug` and then set the `GOLIB_TRACE` environment variable.

```
> set GOLIB_TRACE=github.com/billziss-gh/objfs/fs.*,github.com/billziss-gh/objfs/fs/objfs.*
```

This will print a trace of every file system operation and error encountered. It will give us insights on why the `Rename` operation fails.

(It is also possible to set up [Fiddler](https://www.telerik.com/fiddler) for HTTP debugging if we determine that OneDrive fails the operation. Fiddler must be setup with "Decrypt HTTPS traffic" under Tools > Options > HTTPS and objfs must be launched with the environment variable `http_proxy=127.0.0.1:8888`.)

**Comment by billziss-gh** [comment]
Note that after commit 4483104fa55ffe3026bef5d85626e432c87fe377 trace diagnostics also require the flag `-v` to be set during command line invocation.

**Comment by billziss-gh** [comment]
The objfs diagnostics facility has been revamped. Using it will give insights into troubleshooting issues such as this.

From the [README](https://github.com/billziss-gh/objfs#diagnostics):

>Objfs includes a tracing facility that can be used to troubleshoot problems, to gain insights into its internal workings, etc. This facility is enabled when the `-v` option is used.
>
>The environment variable `GOLIB_TRACE` controls which traces are enabled. This variable accepts a comma separated list of file-style patterns containing wildcards such as `*` and `?`.
>
>```
>$ export GOLIB_TRACE=pattern1,...,patternN
>```
>
>Examples:
>
>```
>$ export GOLIB_TRACE=github.com/billziss-gh/objfs/fs.*      # file system traces
>$ export GOLIB_TRACE=github.com/billziss-gh/objfs/objio.*   # object storage traces
>$ export GOLIB_TRACE=github.com/billziss-gh/objfs/fs.*,github.com/billziss-gh/objfs/objio.*
>$ ./objfs -v -credentials=TOKEN_PATH mount MOUNTPOINT
>```

**Comment by lowleveldesign** [comment]
@billziss-gh great thanks for your help. It looks like the latest build works :)
