### ISSUE TITLE
Saving files to drive causes device io error

### ISSUE THREAD

**Issue by johnsu** [billziss-gh/objfs#2]
I tried saving a new file into a OneDrive storage mounted as t: which resulted in a device io error
<img width="415" alt="bug" src="https://user-images.githubusercontent.com/1093994/38574657-370f60a2-3cae-11e8-9356-6ff4ea5ca9ac.png">

**Comment by billziss-gh** [comment]
Is this a persistent or a transient problem?

This usually happens if there is a networking issue between the client and OneDrive. I am working on making such communication more robust (e.g. by retrying operations, etc).

While testing it is best to run objfs with diagnostics enabled as described in the [README](https://github.com/billziss-gh/objfs#diagnostics):

>Objfs includes a tracing facility that can be used to troubleshoot problems, to gain insights into its internal workings, etc. This facility is enabled when the `-v` option is used.
>
>The environment variable `GOLIB_TRACE` controls which traces are enabled. This variable accepts a comma separated list of file-style patterns containing wildcards such as `*` and `?`.
>
>```
>$ export GOLIB_TRACE=pattern1,...,patternN
>```
>
>Examples:
>
>```
>$ export GOLIB_TRACE=github.com/billziss-gh/objfs/fs.*      # file system traces
>$ export GOLIB_TRACE=github.com/billziss-gh/objfs/objio.*   # object storage traces
>$ export GOLIB_TRACE=github.com/billziss-gh/objfs/fs.*,github.com/billziss-gh/objfs/objio.*
>$ ./objfs -v -credentials=TOKEN_PATH mount MOUNTPOINT
>```

**Comment by johnsu** [comment]
persistent. saving a new file on our platform has never worked

**Comment by billziss-gh** [comment]
Please build the latest version of objfs and run the following:

```
set "GOLIB_TRACE=github.com/billziss-gh/objfs/fs.*,github.com/billziss-gh/objfs/objio.*"
objfs -v -credentials=TOKEN_PATH mount -o FUSE_OPTIONS MOUNTPOINT
```

Post the resulting log here.
