### ISSUE TITLE
Any simple Object Store Servers?

### ISSUE THREAD

**Issue by lonnietc** [billziss-gh/objfs#5]
Hello,

I have just been able to compile objfs.exe on Windows 10 (x64) with Go v1.19.3 and now I wanted to test it, but on some local Windows machines that I have to learn about Object Storage which seems to be in that it splits a single file across multiple Object Storage servers and then collects the parts when needed to access the file.  

To me this seems much like a BitTorrent approach, but I wanted to test it locally so I found a Golang Object Storage server "Minio"

```
https://min.io/
and
https://github.com/minio/minio
```

and was going to give it a try, but wanted to ask if there was an easier way test things locally first.

Thanks and have a great day

**Comment by billziss-gh** [comment]
Objfs currently only supports (some version of) OneDrive and Dropbox.

See [here](https://github.com/winfsp/objfs.pkg) for implementation details.
